#!/usr/bin/env python
#
# Created by Jeremy Bowman on Mon Apr 27 17:05:37 EDT 2015
# Copyright (c) 2015 Safari Books Online. All rights reserved.
#
# This script is always run from the project root

from __future__ import print_function, unicode_literals

import os
import shlex
import subprocess
    

def popen(cmd):
    args = shlex.split(cmd)
    return subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True).stdout

diff = popen('git diff --name-only HEAD@{1} HEAD')
changed_files = {filename.strip() for filename in diff}

if any('git-hooks' in f for f in changed_files):
    # update git hooks
    os.system('git-hooks/install-hooks')

# always delete pyc files
print('Deleting .pyc files in project dir')
os.system("find . -name '*pyc' -delete")

virtual_env = os.environ.get('VIRTUAL_ENV')
if virtual_env:
    python = os.path.join(virtual_env, 'bin', 'python')

    # put stuff that requires virtualenv here

    # delete all .pyc files in the virtual env
    print('Deleting .pyc files in virtualenv')
    os.system("find %s -name '*pyc' -delete" % virtual_env)

    os.system('requirements/clean_up_requirements.py')
    os.system("pip install --disable-pip-version-check --requirement requirements/base.txt")
    os.system("pip install --disable-pip-version-check --requirement requirements/tests.txt")
    os.system("pip install --disable-pip-version-check --editable ./")
